[project]
name = "my-portfolio-site"
version = "0.1.0"
description = "Miguel Fiandor Data Analyst & Engineer Freelance Site"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nikola[extras]>=8.3.1",
]
